# Generated by Django 4.2.13 on 2024-08-12 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Kategorya'),
        ),
        migrations.AddField(
            model_name='product',
            name='categoryScience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryscience', verbose_name='Kategorya Fanlar'),
        ),
    ]
